config/routes.rb
Researchr::Application.routes.draw do
  

  resources :users do
    resources :queries
  end

  #resources :sessions, only: [:new, :create, :destroy]
  get "/login", to: "session#new"
  post "/session", to: "session#create"
  delete "/session", to: "session#destroy"
  get "/about", to: "about#index"
  get "/contact", to: "contact#index"

  root "welcome#index"
end

app/models/query.rb
class Query < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true
  validates :q_string, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :queries, dependent: :destroy
  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  self.has_secure_password()

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  helper_method :current_user, :logged_in?
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController

  before_action :load_user, only: [:index, :create, :show]
  before_action :authenticate, :authorize, except: [:new, :destroy]

  def index
    @query = Query.where(user_id: params[:user_id])
    @listings_data = @query.map do |listing|
      get_data(listing.q_string).merge({'id' => listing.id})
    end
  end

  def new
    @query = Query.new
    render(:new)
  end

  def create
    @query = @user.queries.new(title: params[:title], q_string: create_string(params[:title], params[:zip], params[:beds], params[:baths]))
    if @query.save
      redirect_to ("/users/#{params[:user_id]}/queries")
    else
      render(:new)
    end
  end

  def show
    @query = Query.find(params[:id])
    @result = @query.q_string 
    @api = get_data(@result)
  end

  def destroy
    @query = Query.find_by(id: params[:id])
    @query.destroy
    redirect_to ("/users/#{params[:user_id]}/queries")
  end

  private

  def load_user
    return @user = User.find(params[:user_id])
  end

  def get_data(result)
    from_streeteasy = HTTParty.get(result)
    return from_streeteasy
  end

  def create_string(title, zip, beds, baths)
    return "http://streeteasy.com/nyc/api/#{title}/data?criteria=zip:#{zip}%7Cbeds:#{beds}%7Cbaths:#{baths}&key=#{STREETEASY_CLIENT_ID}&format=json"
  end

  def authenticate
    unless logged_in?
     redirect_to login_path
    end
  end

  def authorize
    unless current_user == @user
      redirect_to login_path
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
    render(:new)
  end

  def create
    # find if any user has that email
    user = User.find_by(email: params[:email])
    
    # if that user exists and it has a password that
    # was sent
    if user && ( user.authenticate(params[:password]) )
      
      # save the user_id in the session hash
      session[:user_id] = user.id

      # and redirect to that user's home page
      redirect_to( user_path(user) )
    else

      # the email/password is wrong!
      @message = "This email and password combination does not exist."
      render(:new)
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :load_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, :authorize, except: [:new, :create]

  def new
    @user = User.new
    render(:new)
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render(:new)
    end
  end

  def show
  end

  def edit
    @update_worked = true
  end

  def update
    @update_worked = @user.update(user_params)
    if @update_worked
      redirect_to user_path(@user)
    else
      render(:edit)
    end
  end

  def destroy
    @user.destroy
    session.destroy
    redirect_to root_path
  end

  private

  def load_user
    return @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
  end

  def authenticate
    unless logged_in?
     redirect_to login_path
    end
  end

  def authorize
    unless current_user == @user
      redirect_to login_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def algo_for_quality(avg_price, avg_sqft)
    if avg_sqft == 0
      return 0
    else
      return (avg_price / avg_sqft)
    end
  end

  def color(algo_for_quality)
    if algo_for_quality > 55
      return "scoregreen"
    elsif algo_for_quality <= 55 && algo_for_quality >= 50
      return "scoreyellow"
    else
      return "scorered"
    end
  end
end

app/views/about/index.html.erb
<div class="about">
<h1>REsearchr</h1>
<h2>The top resource for Real Estate Neighborhood Comparisons</h2>
<p></p>

<p></p>

<p></p>
</div>

app/views/contact/index.html.erb
<br><br><br>

<h1>We can be reached at</h1>

<h1>info[at]researchrapp[dot]com</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Researchr</title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Exo:900' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
<header>
  <img src="/assets/logo.png">
<p><%= link_to "home", root_path %></p>
<p><%= link_to "join", new_user_path %></p>
<p><%= link_to "my account", user_path(User.find_by(id: session[:user_id]))unless session[:user_id].nil? %></p>
<p><%= link_to("login","/login") if session[:user_id].nil? %></p>
<p><%= link_to("logout #{User.find_by(id: session[:user_id]).first_name}", "/session", method: "delete") unless session[:user_id].nil? %></p>

<p><%= link_to "about us", about_path %></p>
<p><%= link_to "contact us", contact_path %></p>
</header>
</div>



<%= yield %>


</body>
</html>

app/views/queries/_form.html.erb
<form action="/users/<%= params[:user_id] %>/queries" method="POST">
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
  <label>
    Sales or Rentals: 
  <select name="title">
    <option value="sales">Sales</option>
    <option value="rentals">Rentals</option>
  </select>
  </label>

  <label>
    NYC Zip:
  <input type="text" name="zip">
  </label>
  
  <label>
    Beds:
  <input type="text" name="beds">
  </label>

  <label>
    Baths:
  <input type="text" name="baths">
  </label>
  <br>
  <button>Submit Search</button>

app/views/queries/index.html.erb
<h1>View all Saved Searches</h1>

<div class="center_table_index">
<div class="caption">All Saved Searches</div>  
<div id="table">
  <div class="header-row row">
    <span class="cell primary">Description</span>
    <span class="cell">Total Listings</span>
    <span class="cell">Avg Price</span>
    <span class="cell">Price 10th Percentile</span>
    <span class="cell">Price 90th Percentile</span>
    <span class="cell">Avg SqFt</span>
    <span class="cell">Avg Price/SqFt</span>
    <span class="cell">Avg Week on Market</span>
    <span class="cell">Raw Data</span>
    <span class="cell">Value Score</span>
    <span class="cell">Action</span>
  </div>
  <% @listings_data.each do |item| %>
    <div class="row">
      <input type="radio" name="expand" />
      <span class="cell primary" data-label="Description"><%= item.fetch("criteria_description") %></span>
      <span class="cell" data-label="Total Listings"><%= item.fetch("listing_count") %></span>
      <span class="cell" data-label="Avg Price"><%=number_to_currency(item.fetch("average_price"), :precision => 0) %></span>
      <span class="cell" data-label="Price 10th Percentile"><%=number_to_currency( item.fetch("percentile_10_price"), :precision => 0) %></span>
      <span class="cell" data-label="Price 90th Percentile"><%=number_to_currency( item.fetch("percentile_90_price"),:precision => 0) %></span>
      <span class="cell" data-label="Avg SqFt"><%= item.fetch("average_sqft") %></span>
      <span class="cell" data-label="Avg Price/SqFt"><%=number_to_currency( item.fetch("average_ppsf"),:precision => 0) %></span>
      <span class="cell" data-label="Avg WOM"><%= item.fetch("average_wom").to_i %></span>
      <span class="cell" data-label="Raw Data"><a href="/users/<%= params[:user_id] %>/queries/<%= item.fetch('id') %>">View</a></span>
      <span class="cell" id="<%= color(algo_for_quality(item.fetch("average_price"), item.fetch("average_ppsf"))) %>" data-label="Value Score"><%= algo_for_quality(item.fetch("average_price"), item.fetch("average_ppsf")) %></span>
      <span class="cell" data-label="Action"><%= form_tag user_query_path(@user, item.fetch('id')),:class => 'del', method: "delete" do %>
        <%= submit_tag("Delete") %>
        <% end %>
      </span>
    </div>
  <% end %>
 </div><br>
 <a class="new-query-button" href="/users/<%= params[:user_id]%>/queries/new">New search query</a>
</div>

app/views/queries/new.html.erb
<h2>Enter your seach parameters here!</h2>

<div class="form">
<% unless @user.nil? || @user.id.nil? %>
  <div id="errors">
    <h3>Errors!</h3>
    <ul>
      <% @user.errors.messages.each do |field,error| %>
        <li><em><%= "#{field.capitalize} #{error.first}!" %></em></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render "form" %>

</div>

app/views/queries/show.html.erb
<h4 class="left"><%= link_to "<< back to queries", user_queries_path(@user) %></h4>
<h1>View Raw Data</h1>


<div class="center_table">
<div class="caption_show"><%= @api.fetch("criteria_description") %></div>  
<div id="table_show">
  <div class="header-row row">
    <span class="cell primary">Name</span>
    <span class="cell">Data</span>

  </div>
  <div class="row">
  <input type="radio" name="expand">
    <span class="cell primary" data-label="Name">Listing Count</span>
    <span class="cell" data-label="Data"><%= @api.fetch("listing_count") %></span>

  </div>
  <div class="row">
  <input type="radio" name="expand">
    <span class="cell primary" data-label="Vehicle">Median Price</span>
    <span class="cell" data-label="Exterior"><%= number_to_currency( @api.fetch("median_price"), :precision => 0) %></span>

  </div>
  <div class="row">
  <input type="radio" name="expand">
    <span class="cell primary" data-label="Vehicle">Average Price</span>
    <span class="cell" data-label="Exterior"><%= number_to_currency( @api.fetch("average_price"),:precision => 0) %></span>

  </div>
  <div class="row">
  <input type="radio" name="expand">
    <span class="cell primary" data-label="Vehicle">Price in 10th Percentile</span>
    <span class="cell" data-label="Exterior"><%= number_to_currency( @api.fetch("percentile_10_price"),:precision => 0) %></span>

  </div>
  <div class="row">
  <input type="radio" name="expand">
    <span class="cell primary" data-label="Vehicle">Price in 90th Percentile</span>
    <span class="cell" data-label="Exterior"><%= number_to_currency( @api.fetch("percentile_90_price"), :precision => 0) %></span>

  </div>
  <div class="row">
  <input type="radio" name="expand">
    <span class="cell primary" data-label="Vehicle">Median Square Feet</span>
    <span class="cell" data-label="Exterior"><%= @api.fetch("median_sqft") %></span>

    </div>
  <div class="row">
  <input type="radio" name="expand">
    <span class="cell primary" data-label="Vehicle">Average Square Feet</span>
    <span class="cell" data-label="Exterior"><%= @api.fetch("average_sqft") %></span>

        </div>
  <div class="row">
  <input type="radio" name="expand">
    <span class="cell primary" data-label="Vehicle">Median Price/SqFt</span>
    <span class="cell" data-label="Exterior"><%= number_to_currency( @api.fetch("median_ppsf"), :precision => 0) %></span>

        </div>
  <div class="row">
  <input type="radio" name="expand">
    <span class="cell primary" data-label="Vehicle">Average Price/SqFt</span>
    <span class="cell" data-label="Exterior"><%= number_to_currency( @api.fetch("average_ppsf"), :precision => 0) %></span>

        </div>
  <div class="row">
  <input type="radio" name="expand">
    <span class="cell primary" data-label="Vehicle">Median Weeks on Market</span>
    <span class="cell" data-label="Exterior"><%= @api.fetch("median_wom") %></span>

        </div>
  <div class="row">
  <input type="radio" name="expand">
    <span class="cell primary" data-label="Vehicle">Average Weeks on Market</span>
    <span class="cell" data-label="Exterior"><%= @api.fetch("average_wom") %></span>

        </div>
  <div class="row">
  <input type="radio" name="expand">
    <span class="cell primary" data-label="Vehicle">Value Score</span>
    <span class="cell" id="<%= color(algo_for_quality(@api.fetch("average_price"), @api.fetch("average_ppsf"))) %>" data-label="Exterior"><%= algo_for_quality(@api.fetch("average_price"), @api.fetch("average_ppsf")) %></span>

        </div>      
  <div class="row">
  <input type="radio" name="expand">
    <span class="cell primary" data-label="Vehicle">Search Criteria</span>
    <span class="cell" data-label="Exterior"><%= @api.fetch("criteria") %></span>

        </div>
  <div class="row">
  <input type="radio" name="expand">
    <span class="cell primary" data-label="Vehicle">Search URL</span>
    <span class="cell" data-label="Exterior"><%= link_to("View All Listings", @api.fetch("search_url")) %></span>
    
  </div>
</div>
</div>
<br>
<div class="center show-delete">
<%= form_tag user_query_path(@user, @query), method: "delete" do %>
  <%= submit_tag("Delete Query") %>
<% end %>
</div>
<br><br>

app/views/session/new.html.erb
<h2>Login below!</h2>

<div class="form">
<% unless @message.nil? %>
  <div id="errors">
    <h3>Errors!</h3>
    <ul>
      <li><em><%= @message %></em></li>
    </ul>
  </div>
<% end %>

<%= form_tag "/session" do %>
  <%= label_tag :email %>
  <%= email_field_tag :email %>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <br>
  <div class="login">
  <%= submit_tag "Log in!" %>
</div>
<% end %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <br/>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <br/>

  <%= f.label :email %>
  <%= f.email_field :email %>
  <br/>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br/>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br/>


  <div class="join">
  <%= f.submit @user.id.nil? ? "Join!" : "Save Changes" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2>Update user <%= @user.email %></h2>

<div class="form">
<% unless @update_worked %>
  <div id="errors">
    <h3>Errors!</h3>
    <ul>
      <% @user.errors.messages.each do |field,error| %>
        <li><em><%= "#{field.capitalize} #{error.first}!" %></em></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render "form" %>


</div>

app/views/users/new.html.erb
<h2>Create your account here!</h2>

<div class="form">
<% unless @user.errors.messages.empty? %>
  <div id="errors">
    <h3>Errors!</h3>
    <ul>
      <% @user.errors.messages.each do |field,error| %>
        <li><em><%= "#{field.capitalize} #{error.first}!" %></em></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render "form" %>

</div>

app/views/users/show.html.erb
<h2>Welcome <%= @user.first_name %>!</h2>

<div class="form_user">
<p class="tile"><%= link_to "Edit My Info", edit_user_path(@user) %></p>
<p class="tile"><%= link_to "Enter a new query", new_user_query_path(@user) %></p>
<p class="tile"><%= link_to "View Saved Searches", user_queries_path(@user) %></p>
<p>Account Created: <%= @user.created_at%></p>
<p>Account Update on: <%= @user.updated_at%></p>
<div class="deleteaccount">
<%= form_tag user_path(@user), method: "delete" do %>
  <%= submit_tag("Delete My Account") %>
</div>
<% end %>
</div>

app/views/welcome/index.html.erb
<div class="background">
<img src="/assets/bk2.jpg">
</div>
<br><br><br>
<div class="text">
    <div class="border">
      <span>Welcome to REsearchr</span><br>
    </div>
  <span class="sm">NYC Real Estate Neighborhood Comparisons</span>
</div>
<div class="wrapper">
  <div class="home-button">
    <a href="/users/new">Join</a>
  </div>
  <div class="home-button">
    <a href="/login">Login</a>
  </div>
</div>  